version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/django_project
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: postgresql_db
    image: postgres
    restart: always 
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
